DROP TABLE IF EXISTS CLASS;

CREATE TABLE CLASS (
    id INT PRIMARY KEY,
    name VARCHAR(50),
    age INT NOT NULL
);

INSERT INTO CLASS VALUES (1, 'ALI', 26);
INSERT INTO CLASS VALUES (2, 'MUZAMILL', 20);

SELECT * FROM CLASS;
